FROM nginx

# install dependencies
WORKDIR /usr/share/nginx/html
# COPY . ./html/baywatch-origin.git

RUN apt-get update && apt-get install nano git fcgiwrap apache2-utils -y \
	&& mkdir git \
	&& chown -R www-data:www-data git \
	&& htpasswd -c git/htpasswd devuser \
	&& mkdir git/baywatch-origin \
	&& cd git/baywatch-origin \
	&& git --bare init

WORKDIR /usr/share/nginx/html/git/baywatch-origin

#COPY . /usr/share/nginx/html/git/baywatch-origin
COPY . .

COPY ./setup/nginx.conf /etc/nginx
COPY ./setup/baywatch-origin.nginx.conf /etc/nginx/conf.d


RUN chown -R www-data:www-data . \
	&& chmod -R 755 . \
	&& git update-server-info
	# && spawn-fcgi -s /var/run/fcgiwrap.sock /usr/sbin/fcgiwrap
#	&& service fcgiwrap restart

# ENTRYPOINT service fcgiwrap restart
CMD ["nginx", "-g", "daemon off;"]
CMD ["service", "fcgiwrap", "restart"]

EXPOSE 80