import Bay1Qr from './images/shortbayqr/bay1short.png'
import Bay2Qr from './images/shortbayqr/bay2short.png'
import Bay3Qr from './images/shortbayqr/bay3short.png'
import Bay4Qr from './images/shortbayqr/bay4short.png'
import Bay5Qr from './images/shortbayqr/bay5short.png'
import Bay6Qr from './images/shortbayqr/bay6short.png'
export Bay7Qr from './images/shortbayqr/bay7short.png'
export Bay8Qr from './images/shortbayqr/bay8short.png'
export Bay9Qr from './images/shortbayqr/bay9short.png'
export Bay1Qr from './images/shortbayqr/bay10short.png'
export Bay11Qr from './images/shortbayqr/bay11short.png'
export Bay12Qr from './images/shortbayqr/bay12short.png'
export Bay13Qr from './images/shortbayqr/bay13short.png'
export BaycrQr from './images/shortbayqr/baycrshort.png'

